server:
  port: 8222

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      websocket:
        enabled: true
      routes:


      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:4200" # Allow requests from Angular app
              - "http://localhost:*"  # For WebSocket connections

            allowed-methods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"
            allow-credentials: true
            max-age: 3600 # Cache preflight response for 1 hour

